// Datos mock para desarrollo - sincronizado con la base de datos
const mockTeachers = [
  {
    id: 1,
    name: 'Alberto García',
    dni: '12345678A',
    hiringYear: 2019,
    imageUrl: 'https://res.cloudinary.com/dltofstl9/image/upload/v1776166675/Alberto_dtofxc.png',
    specialties: ['Circuit', 'Zumba'],
    activities: [1, 2],
    activityCount: 2,
    isActive: true,
    active: true,
  },
  {
    id: 2,
    name: 'Melissa Gómez',
    dni: '23456789B',
    hiringYear: 2021,
    imageUrl: 'https://res.cloudinary.com/dltofstl9/image/upload/v1776166674/Melissa_r6i9cr.png',
    specialties: ['Bike'],
    activities: [3, 4],
    activityCount: 2,
    isActive: true,
    active: true,
  },
  {
    id: 3,
    name: 'Javier Galván',
    dni: '34567890C',
    hiringYear: 2020,
    imageUrl: 'https://res.cloudinary.com/dltofstl9/image/upload/v1776166673/Javier_wx64jj.png',
    specialties: ['CrossTraining'],
    activities: [5, 6],
    activityCount: 2,
    isActive: true,
    active: true,
  },
  {
    id: 4,
    name: 'María Regueiro',
    dni: '45678901D',
    hiringYear: 2022,
    imageUrl: 'https://res.cloudinary.com/dltofstl9/image/upload/v1776166672/Maria_z1drrf.png',
    specialties: ['Aquafit'],
    activities: [7, 8],
    activityCount: 2,
    isActive: true,
    active: true,
  },
  {
    id: 5,
    name: 'Ana Morandeira',
    dni: '56789012E',
    hiringYear: 2023,
    imageUrl: 'https://res.cloudinary.com/dltofstl9/image/upload/v1776166671/Ana_tsudsq.png',
    specialties: ['Pilates'],
    activities: [9, 10],
    activityCount: 2,
    isActive: true,
    active: true,
  },
];

export const teacherService = {
  getAll: () => Promise.resolve({ data: mockTeachers }),
  getById: (id) => Promise.resolve({ data: mockTeachers.find(t => t.id === id) }),
  create: (data) => Promise.resolve({ data: { id: Date.now(), ...data, activities: [], activityCount: 0 } }),
  update: (id, data) => Promise.resolve({ data: { id, ...data } }),
  delete: (id) => Promise.resolve({ data: { success: true } }),
};

export default { get: () => {}, post: () => {}, put: () => {}, delete: () => {} };
